version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  django:
    build: ./django
    container_name: django_app
    volumes:
      - ./django/src:/app
      - django_static:/app/static
      - django_media:/app/media
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      DB_NAME: mydatabase
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_HOST: db
      DB_PORT: 5432

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - django_static:/vol/static
      - django_media:/vol/media
    depends_on:
      - django

volumes:
  django_static:
  django_media:
  postgres_data:
